ALTER SESSION SET "_oracle_script"=true;
ALTER SESSION SET CONTAINER = XEPDB1;

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
CREATE ROLE RL_QLHSUT_UNGVIEN;
CREATE ROLE RL_QLHSUT_NHANVIEN;
CREATE ROLE RL_QLHSUT_DOANHNGHIEP;
ALTER SESSION SET "_ORACLE_SCRIPT" = FALSE;
c
-- TẠO PROCS
-- proc xóa user doanh nghiệp
CREATE OR REPLACE PROCEDURE SYS.USP_DROPUSER_QLHSUT_DOANHNGHIEP
AS
    CURSOR CUR IS (SELECT TO_CHAR(MADN)
                    FROM QLHSUT.QLHSUT_DOANH_NGHIEP
                    WHERE TO_CHAR(MADN) IN (SELECT USERNAME FROM ALL_USERS)
                    );
    STRSQL VARCHAR2(2000);
    N2 VARCHAR2(6);
BEGIN
    OPEN CUR;
    LOOP
        FETCH CUR INTO N2;
        EXIT WHEN CUR%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(N2);
            
        STRSQL := 'DROP USER "'||N2||'" CASCADE';
        EXECUTE IMMEDIATE(STRSQL);
    END LOOP;
    CLOSE CUR;
END;
/
-- proc xóa user ứng viên
CREATE OR REPLACE PROCEDURE SYS.USP_DROPUSER_QLHSUT_UNGVIEN
AS
    CURSOR CUR IS (SELECT TO_CHAR(MAUV)
                    FROM QLHSUT.QLHSUT_UNG_VIEN
                    WHERE TO_CHAR(MAUV) IN (SELECT USERNAME FROM ALL_USERS)
                    );
    STRSQL VARCHAR2(2000);
    N2 VARCHAR2(8);
BEGIN
    OPEN CUR;
    LOOP
        FETCH CUR INTO N2;
        EXIT WHEN CUR%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(N2);
            
        STRSQL := 'DROP USER "'||N2||'" CASCADE';
        EXECUTE IMMEDIATE(STRSQL);
    END LOOP;
    CLOSE CUR;
END;
/
-- proc xóa user nhân viên
CREATE OR REPLACE PROCEDURE SYS.USP_DROPUSER_QLHSUT_NHANVIEN
AS
    CURSOR CUR IS (SELECT TO_CHAR(MANV)
                    FROM QLHSUT.QLHSUT_NHAN_VIEN
                    WHERE TO_CHAR(MANV) IN (SELECT USERNAME FROM ALL_USERS)
                    );
    STRSQL VARCHAR2(2000);
    N2 VARCHAR2(8);
BEGIN
    OPEN CUR;
    LOOP
        FETCH CUR INTO N2;
        EXIT WHEN CUR%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(N2);
            
        STRSQL := 'DROP USER "'||N2||'" CASCADE';
        EXECUTE IMMEDIATE(STRSQL);
    END LOOP;
    CLOSE CUR;
END;
/

-- proc tạo user nhân viên
CREATE OR REPLACE PROCEDURE SYS.USP_CREATEUSER_QLHSUT_NHANVIEN
AS
    CURSOR CUR IS (SELECT TO_CHAR(MANV)
                    FROM QLHSUT.QLHSUT_NHAN_VIEN
                    WHERE TO_CHAR(MANV) NOT IN (SELECT USERNAME FROM ALL_USERS)
                    );
    STRSQL VARCHAR2(2000);
    N2 VARCHAR2(6);
BEGIN
    OPEN CUR;
    LOOP
        FETCH CUR INTO N2;
        EXIT WHEN CUR%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(N2);
            
        STRSQL := 'CREATE USER "'||N2||'" IDENTIFIED BY "' || 123456 || '" CONTAINER = CURRENT';
        EXECUTE IMMEDIATE(STRSQL);
        STRSQL := 'GRANT CONNECT, RESOURCE, RESTRICTED SESSION TO "'|| N2 || '"';
        EXECUTE IMMEDIATE(STRSQL);
    END LOOP;
    CLOSE CUR;
END;
/
-- proc tạo user ứng viên
CREATE OR REPLACE PROCEDURE SYS.USP_CREATEUSER_QLHSUT_UNGVIEN
AS
    CURSOR CUR IS (SELECT TO_CHAR(MAUV)
                    FROM QLHSUT.QLHSUT_UNG_VIEN
                    WHERE TO_CHAR(MAUV) NOT IN (SELECT USERNAME FROM ALL_USERS)
                    );
    STRSQL VARCHAR2(2000);
    N2 VARCHAR2(6);
BEGIN
    OPEN CUR;
    LOOP
        FETCH CUR INTO N2;
        EXIT WHEN CUR%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(N2);
            
        STRSQL := 'CREATE USER "'||N2||'" IDENTIFIED BY "' || 123456 || '" CONTAINER = CURRENT';
        EXECUTE IMMEDIATE(STRSQL);
        STRSQL := 'GRANT CONNECT, RESOURCE, RESTRICTED SESSION TO "'|| N2 || '"';
        EXECUTE IMMEDIATE(STRSQL);
    END LOOP;
    CLOSE CUR;
END;
/
-- proc tạo user doanh nghiệp
CREATE OR REPLACE PROCEDURE SYS.USP_CREATEUSER_QLHSUT_DOANHNGHIEP
AS
    CURSOR CUR IS (SELECT TO_CHAR(MADN)
                    FROM QLHSUT.QLHSUT_DOANH_NGHIEP
                    WHERE TO_CHAR(MADN) NOT IN (SELECT USERNAME FROM ALL_USERS)
                    );
    STRSQL VARCHAR2(2000);
    N2 VARCHAR2(6);
BEGIN
    OPEN CUR;
    LOOP
        FETCH CUR INTO N2;
        EXIT WHEN CUR%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(N2);
            
        STRSQL := 'CREATE USER "'||N2||'" IDENTIFIED BY "' || 123456 || '" CONTAINER = CURRENT';
        EXECUTE IMMEDIATE(STRSQL);
        STRSQL := 'GRANT CONNECT, RESOURCE, RESTRICTED SESSION TO "'|| N2 || '"';
        EXECUTE IMMEDIATE(STRSQL);
    END LOOP;
    CLOSE CUR;
END;
/

-- proc gán role RL_QLHSUT_NHANVIEN
CREATE OR REPLACE PROCEDURE SYS.USP_GRANTROLE_QLHSUT_NHANVIEN
    (STRROLE VARCHAR2)
AS
    CURSOR CUR IS (SELECT TO_CHAR(MANV)
                    FROM QLHSUT.QLHSUT_NHAN_VIEN
                    WHERE TO_CHAR(MANV) IN (SELECT USERNAME
                                        FROM ALL_USERS));
    STRSQL VARCHAR2(2000);
    N2 VARCHAR2(8);
BEGIN
    OPEN CUR;
    LOOP
        FETCH CUR INTO N2;
        EXIT WHEN CUR%NOTFOUND;
        
        STRSQL := 'GRANT "'||STRROLE||'" TO "'||N2||'"';
        EXECUTE IMMEDIATE (STRSQL);
    END LOOP;
    CLOSE CUR;
END;
/
-- proc gán role RL_QLHSUT_UNGVIEN
CREATE OR REPLACE PROCEDURE SYS.USP_GRANTROLE_QLHSUT_UNGVIEN
    (STRROLE VARCHAR2)
AS
    CURSOR CUR IS (SELECT TO_CHAR(MAUV)
                    FROM QLHSUT.QLHSUT_UNG_VIEN
                    WHERE TO_CHAR(MAUV) IN (SELECT USERNAME
                                        FROM ALL_USERS));
    STRSQL VARCHAR2(2000);
    N2 VARCHAR2(8);
BEGIN
    OPEN CUR;
    LOOP
        FETCH CUR INTO N2;
        EXIT WHEN CUR%NOTFOUND;
        
        STRSQL := 'GRANT "'||STRROLE||'" TO "'||N2||'"';
        EXECUTE IMMEDIATE (STRSQL);
    END LOOP;
    CLOSE CUR;
END;
/
-- proc gán role RL_QLHSUT_UNGVIEN
CREATE OR REPLACE PROCEDURE SYS.USP_GRANTROLE_QLHSUT_DOANHNGHIEP
    (STRROLE VARCHAR2)
AS
    CURSOR CUR IS (SELECT TO_CHAR(MADN)
                    FROM QLHSUT.QLHSUT_DOANH_NGHIEP
                    WHERE TO_CHAR(MADN) IN (SELECT USERNAME
                                        FROM ALL_USERS));
    STRSQL VARCHAR2(2000);
    N2 VARCHAR2(8);
BEGIN
    OPEN CUR;
    LOOP
        FETCH CUR INTO N2;
        EXIT WHEN CUR%NOTFOUND;
        
        STRSQL := 'GRANT "'||STRROLE||'" TO "'||N2||'"';
        EXECUTE IMMEDIATE (STRSQL);
    END LOOP;
    CLOSE CUR;
END;
/
-- THỰC THI PROCS
-- DROP USER
BEGIN 
    SYS.USP_DROPUSER_QLHSUT_DOANHNGHIEP;
END;
/

BEGIN 
    SYS.USP_DROPUSER_QLHSUT_UNGVIEN;
END;
/

BEGIN 
    SYS.USP_DROPUSER_QLHSUT_NHANVIEN;
END;
/
-- CREATE USER
BEGIN 
    SYS.USP_CREATEUSER_QLHSUT_NHANVIEN;
END;
/

BEGIN 
    SYS.USP_CREATEUSER_QLHSUT_UNGVIEN;
END;
/

BEGIN 
    USP_CREATEUSER_QLHSUT_DOANHNGHIEP;
END;
/

BEGIN SYS.USP_GRANTROLE_QLHSUT_UNGVIEN('RL_QLHSUT_UNGVIEN'); END;
/
BEGIN SYS.USP_GRANTROLE_QLHSUT_NHANVIEN('RL_QLHSUT_NHANVIEN'); END;
/
BEGIN SYS.USP_GRANTROLE_QLHSUT_DOANHNGHIEP('RL_QLHSUT_DOANHNGHIEP'); END;
/

--------------------------------------------------------------------------------
-- CẤP CÁC QUYỀN CẦN THIẾT 
--------------------------------------------------------------------------------
-- NHÂN VIÊN
GRANT SELECT ON QLHSUT.QLHSUT_NGUOI_DAI_DIEN TO RL_QLHSUT_NHANVIEN;
GRANT SELECT ON QLHSUT.QLHSUT_DOANH_NGHIEP TO RL_QLHSUT_NHANVIEN;
GRANT SELECT ON QLHSUT.QLHSUT_NHAN_VIEN TO RL_QLHSUT_NHANVIEN;
GRANT SELECT ON QLHSUT.QLHSUT_UNG_VIEN TO RL_QLHSUT_NHANVIEN;
GRANT SELECT ON QLHSUT.QLHSUT_THONG_TIN_DANG_TUYEN TO RL_QLHSUT_NHANVIEN;
GRANT SELECT ON QLHSUT.QLHSUT_THONG_TIN_UU_DAI TO RL_QLHSUT_NHANVIEN;
GRANT SELECT ON QLHSUT.QLHSUT_HOP_DONG_DANG_TUYEN TO RL_QLHSUT_NHANVIEN;
GRANT SELECT ON QLHSUT.QLHSUT_HINH_THUC_DANG_TUYEN TO RL_QLHSUT_NHANVIEN;
GRANT SELECT ON QLHSUT.QLHSUT_HINH_THUC_LUA_CHON TO RL_QLHSUT_NHANVIEN;
GRANT SELECT ON QLHSUT.QLHSUT_PHIEU_QUANG_CAO TO RL_QLHSUT_NHANVIEN;
GRANT SELECT ON QLHSUT.QLHSUT_THONG_TIN_THANH_TOAN TO RL_QLHSUT_NHANVIEN;
GRANT SELECT ON QLHSUT.QLHSUT_HOA_DON TO RL_QLHSUT_NHANVIEN;
GRANT SELECT ON QLHSUT.QLHSUT_HO_SO_UNG_TUYEN TO RL_QLHSUT_NHANVIEN;
GRANT SELECT ON QLHSUT.QLHSUT_THONG_TIN_CHUNG_TU TO RL_QLHSUT_NHANVIEN;
GRANT SELECT ON QLHSUT.QLHSUT_THONG_TIN_BANG_CAP TO RL_QLHSUT_NHANVIEN;

GRANT INSERT, DELETE, UPDATE ON QLHSUT.QLHSUT_NGUOI_DAI_DIEN TO RL_QLHSUT_NHANVIEN;
GRANT INSERT, DELETE, UPDATE ON QLHSUT.QLHSUT_DOANH_NGHIEP TO RL_QLHSUT_NHANVIEN;
GRANT INSERT, DELETE, UPDATE ON QLHSUT.QLHSUT_NHAN_VIEN TO RL_QLHSUT_NHANVIEN;
GRANT INSERT, DELETE, UPDATE ON QLHSUT.QLHSUT_UNG_VIEN TO RL_QLHSUT_NHANVIEN;
GRANT INSERT, DELETE, UPDATE ON QLHSUT.QLHSUT_THONG_TIN_DANG_TUYEN TO RL_QLHSUT_NHANVIEN;
GRANT INSERT, DELETE, UPDATE ON QLHSUT.QLHSUT_THONG_TIN_UU_DAI TO RL_QLHSUT_NHANVIEN;
GRANT INSERT, DELETE, UPDATE ON QLHSUT.QLHSUT_HOP_DONG_DANG_TUYEN TO RL_QLHSUT_NHANVIEN;
GRANT INSERT, DELETE, UPDATE ON QLHSUT.QLHSUT_HINH_THUC_DANG_TUYEN TO RL_QLHSUT_NHANVIEN;
GRANT INSERT, DELETE, UPDATE ON QLHSUT.QLHSUT_HINH_THUC_LUA_CHON TO RL_QLHSUT_NHANVIEN;
GRANT INSERT, DELETE, UPDATE ON QLHSUT.QLHSUT_PHIEU_QUANG_CAO TO RL_QLHSUT_NHANVIEN;
GRANT INSERT, DELETE, UPDATE ON QLHSUT.QLHSUT_THONG_TIN_THANH_TOAN TO RL_QLHSUT_NHANVIEN;
GRANT INSERT, DELETE, UPDATE ON QLHSUT.QLHSUT_HOA_DON TO RL_QLHSUT_NHANVIEN;
GRANT INSERT, DELETE, UPDATE ON QLHSUT.QLHSUT_HO_SO_UNG_TUYEN TO RL_QLHSUT_NHANVIEN;
GRANT INSERT, DELETE, UPDATE ON QLHSUT.QLHSUT_THONG_TIN_CHUNG_TU TO RL_QLHSUT_NHANVIEN;
GRANT INSERT, DELETE, UPDATE ON QLHSUT.QLHSUT_THONG_TIN_BANG_CAP TO RL_QLHSUT_NHANVIEN;
-- ỨNG VIÊN
GRANT SELECT ON QLHSUT.QLHSUT_NGUOI_DAI_DIEN TO RL_QLHSUT_UNGVIEN;
GRANT SELECT ON QLHSUT.QLHSUT_DOANH_NGHIEP TO RL_QLHSUT_UNGVIEN;
GRANT SELECT ON QLHSUT.QLHSUT_NHAN_VIEN TO RL_QLHSUT_UNGVIEN;
GRANT SELECT ON QLHSUT.QLHSUT_UNG_VIEN TO RL_QLHSUT_UNGVIEN;
GRANT SELECT ON QLHSUT.QLHSUT_THONG_TIN_DANG_TUYEN TO RL_QLHSUT_UNGVIEN;
GRANT SELECT ON QLHSUT.QLHSUT_THONG_TIN_UU_DAI TO RL_QLHSUT_UNGVIEN;
GRANT SELECT ON QLHSUT.QLHSUT_HOP_DONG_DANG_TUYEN TO RL_QLHSUT_UNGVIEN;
GRANT SELECT ON QLHSUT.QLHSUT_HINH_THUC_DANG_TUYEN TO RL_QLHSUT_UNGVIEN;
GRANT SELECT ON QLHSUT.QLHSUT_HINH_THUC_LUA_CHON TO RL_QLHSUT_UNGVIEN;
GRANT SELECT ON QLHSUT.QLHSUT_PHIEU_QUANG_CAO TO RL_QLHSUT_UNGVIEN;
GRANT SELECT ON QLHSUT.QLHSUT_THONG_TIN_THANH_TOAN TO RL_QLHSUT_UNGVIEN;
GRANT SELECT ON QLHSUT.QLHSUT_HOA_DON TO RL_QLHSUT_UNGVIEN;
GRANT SELECT ON QLHSUT.QLHSUT_HO_SO_UNG_TUYEN TO RL_QLHSUT_UNGVIEN;
GRANT SELECT ON QLHSUT.QLHSUT_THONG_TIN_CHUNG_TU TO RL_QLHSUT_UNGVIEN;
GRANT SELECT ON QLHSUT.QLHSUT_THONG_TIN_BANG_CAP TO RL_QLHSUT_UNGVIEN;

GRANT INSERT, UPDATE ON QLHSUT.QLHSUT_UNG_VIEN TO RL_QLHSUT_UNGVIEN;
GRANT INSERT, UPDATE ON QLHSUT.QLHSUT_HO_SO_UNG_TUYEN TO RL_QLHSUT_UNGVIEN;
GRANT INSERT, UPDATE ON QLHSUT.QLHSUT_THONG_TIN_CHUNG_TU TO RL_QLHSUT_UNGVIEN;
GRANT INSERT, UPDATE ON QLHSUT.QLHSUT_THONG_TIN_BANG_CAP TO RL_QLHSUT_UNGVIEN;
-- DOANH NGHIỆP
GRANT SELECT ON QLHSUT.QLHSUT_NGUOI_DAI_DIEN TO RL_QLHSUT_DOANHNGHIEP;
GRANT SELECT ON QLHSUT.QLHSUT_DOANH_NGHIEP TO RL_QLHSUT_DOANHNGHIEP;
GRANT SELECT ON QLHSUT.QLHSUT_NHAN_VIEN TO RL_QLHSUT_DOANHNGHIEP;
GRANT SELECT ON QLHSUT.QLHSUT_UNG_VIEN TO RL_QLHSUT_DOANHNGHIEP;
GRANT SELECT ON QLHSUT.QLHSUT_THONG_TIN_DANG_TUYEN TO RL_QLHSUT_DOANHNGHIEP;
GRANT SELECT ON QLHSUT.QLHSUT_THONG_TIN_UU_DAI TO RL_QLHSUT_DOANHNGHIEP;
GRANT SELECT ON QLHSUT.QLHSUT_HOP_DONG_DANG_TUYEN TO RL_QLHSUT_DOANHNGHIEP;
GRANT SELECT ON QLHSUT.QLHSUT_HINH_THUC_DANG_TUYEN TO RL_QLHSUT_DOANHNGHIEP;
GRANT SELECT ON QLHSUT.QLHSUT_HINH_THUC_LUA_CHON TO RL_QLHSUT_DOANHNGHIEP;
GRANT SELECT ON QLHSUT.QLHSUT_PHIEU_QUANG_CAO TO RL_QLHSUT_DOANHNGHIEP;
GRANT SELECT ON QLHSUT.QLHSUT_THONG_TIN_THANH_TOAN TO RL_QLHSUT_DOANHNGHIEP;
GRANT SELECT ON QLHSUT.QLHSUT_HOA_DON TO RL_QLHSUT_DOANHNGHIEP;
GRANT SELECT ON QLHSUT.QLHSUT_HO_SO_UNG_TUYEN TO RL_QLHSUT_DOANHNGHIEP;
GRANT SELECT ON QLHSUT.QLHSUT_THONG_TIN_CHUNG_TU TO RL_QLHSUT_DOANHNGHIEP;
GRANT SELECT ON QLHSUT.QLHSUT_THONG_TIN_BANG_CAP TO RL_QLHSUT_DOANHNGHIEP;

GRANT INSERT, DELETE, UPDATE ON QLHSUT.QLHSUT_NGUOI_DAI_DIEN TO RL_QLHSUT_DOANHNGHIEP;
GRANT INSERT, DELETE, UPDATE ON QLHSUT.QLHSUT_DOANH_NGHIEP TO RL_QLHSUT_DOANHNGHIEP;
GRANT INSERT, DELETE, UPDATE ON QLHSUT.QLHSUT_THONG_TIN_DANG_TUYEN TO RL_QLHSUT_DOANHNGHIEP;
GRANT INSERT, DELETE, UPDATE ON QLHSUT.QLHSUT_THONG_TIN_UU_DAI TO RL_QLHSUT_DOANHNGHIEP;
GRANT INSERT, DELETE, UPDATE ON QLHSUT.QLHSUT_HOP_DONG_DANG_TUYEN TO RL_QLHSUT_DOANHNGHIEP;
GRANT INSERT, DELETE, UPDATE ON QLHSUT.QLHSUT_HINH_THUC_DANG_TUYEN TO RL_QLHSUT_DOANHNGHIEP;
GRANT INSERT, DELETE, UPDATE ON QLHSUT.QLHSUT_PHIEU_QUANG_CAO TO RL_QLHSUT_DOANHNGHIEP;
